name: tabplugin
main: startup.prim.Main
author: UncleMole
version: 1.1.0

commands:
  toggle:
    description: Tab plugin command to adjust plugin.
    usage: /<command> [update/toggle] [deaths/ping]
    permission: